Fix: docker-compose 방식 폐기

diff --git a/be/Jenkinsfile b/be/Jenkinsfile
--- a/be/Jenkinsfile
+++ b/be/Jenkinsfile
@@ -27,31 +27,45 @@ pipeline{
             }
         }
 
-	stage('Deploy Docker'){
+        stage('Gradle Build'){
             steps{
-                script{
-                    sh "docker-compose -f docker-compose.yml pull be"
-                    sh "COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1"
-                    sh "docker-compose -f docker-compose.yml build be --build-arg JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_KEY} --no-cache"
-                    sh "docker-compose -f docker-compose.yml up be -d --remove-orphans"
+                dir('be/'){
+                    sh 'chmod +x ./gradlew'
+                    sh './gradlew clean build -x test'
                 }
             }
         }
 
-        stage('Finish'){
+        stage('Build Docker Image'){
             steps{
                 script{
-                    sh "docker rmi -f \$(docker images -f \"dangling=true\" -q) || true"
+                    sh "docker build -t ${IMAGE_NAME}:${env.BUILD_NUMBER} --build-arg JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_KEY} be/"
                 }
             }
         }
-    }
-    post {
-	success {
-	    echo 'Deployment completed successfully.'
-	}
-	failure {
-	    echo 'Deployment failed.'
-	}
+
+        stage('Deploy Docker'){
+            steps{
+                script {
+                    // 기존 컨테이너가 있으면 중지하고 삭제
+                    sh "docker rm -f ${CONTAINER_NAME} || true"
+
+                    // 새로운 Docker 컨테이너 실행
+                    sh "docker run --name ${CONTAINER_NAME} -d --network db ${IMAGE_NAME}:${env.BUILD_NUMBER} -e JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_KEY} -e JAVA_OPTS='-Djasypt.encryptor.password=${JASYPT_KEY}'"
+                    
+                    // 사용하지 않는 Docker 이미지를 정리
+                    sh "docker image prune -a -f || true"
+                }
+            }
+
+            post {
+                success {
+                    echo 'Deployment completed successfully.'
+                }
+                failure {
+                    echo 'Deployment failed.'
+                }
+            }
+        }
     }
 }
